### ISSUE TITLE
check version nueva

### ISSUE THREAD

**Issue by yellowmachine** [yellowmachine/qwikmpd#88]
```bash
#!/bin/bash

# --- Configuración ---
REPO_URL="https://github.com/tu_usuario/tu_repo.git" # ¡CAMBIA ESTO por la URL de tu repo!
APP_SERVICE_NAME="my_app" # ¡CAMBIA ESTO por el nombre de tu servicio de app en docker-compose.yml!
GIT_BRANCH="main"
WORK_DIR="/tmp/repo_check"
LOG_FILE="/var/log/app_version_check.log" # Ruta para los logs dentro del contenedor

# --- Funciones ---

# Función para registrar mensajes
log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
}

# --- Lógica principal ---

log_message "Iniciando chequeo de nueva versión para $APP_SERVICE_NAME..."

# Crear o limpiar directorio de trabajo
mkdir -p "$WORK_DIR"
cd "$WORK_DIR" || { log_message "Error: No se pudo cambiar al directorio de trabajo $WORK_DIR"; exit 1; }

# Clonar o hacer pull del repositorio para obtener el HEAD más reciente sin descargar todo el historial
# Usamos --depth 1 para solo obtener el último commit
if [ -d ".git" ]; then
    log_message "Repository already cloned, fetching latest commit..."
    git fetch origin "$GIT_BRANCH" || { log_message "Error: No se pudo hacer fetch del repositorio."; exit 1; }
else
    log_message "Cloning repository $REPO_URL..."
    git clone --depth 1 --branch "$GIT_BRANCH" "$REPO_URL" . || { log_message "Error: No se pudo clonar el repositorio."; exit 1; }
fi

# Obtener el SHA del último commit de la rama remota
LATEST_REMOTE_SHA=$(git rev-parse "origin/$GIT_BRANCH")
if [ -z "$LATEST_REMOTE_SHA" ]; then
    log_message "Error: No se pudo obtener el SHA del commit remoto."
    exit 1
fi

# Obtener el SHA del commit actual que está desplegado (asumimos que está en un archivo)
# Esta es una estrategia simple. Podrías leer el commit actual de tu imagen Docker o de un archivo.
# Para este ejemplo, asumimos que 'current_deployed_sha.txt' guarda el último SHA desplegado.
DEPLOYED_SHA_FILE="/data/current_deployed_sha.txt" # Asegúrate que este path esté mapeado a un volumen persistente

# Leer el SHA del último despliegue (si existe)
if [ -f "$DEPLOYED_SHA_FILE" ]; then
    CURRENT_DEPLOYED_SHA=$(cat "$DEPLOYED_SHA_FILE")
    log_message "SHA actual desplegado: $CURRENT_DEPLOYED_SHA"
else
    CURRENT_DEPLOYED_SHA=""
    log_message "No se encontró un SHA desplegado previamente. Consideraremos esto como el primer despliegue o un despliegue inicial."
fi

# Comparar SHAs
if [ "$LATEST_REMOTE_SHA" != "$CURRENT_DEPLOYED_SHA" ]; then
    log_message "¡Nueva versión detectada!"
    log_message "SHA remoto: $LATEST_REMOTE_SHA"
    log_message "SHA actual: $CURRENT_DEPLOYED_SHA"

    # --- Acciones de Actualización ---
    # Es crucial que estos comandos se ejecuten en el host Docker o con permisos apropiados.
    # Usaremos 'docker-compose' para actualizar tu app.
    # El `exec` es porque este script corre DENTRO de un contenedor y necesita comunicarse con el daemon Docker del host.

    log_message "Iniciando actualización de la aplicación $APP_SERVICE_NAME..."

    # Opción 1: Si tu app se construye desde el Dockerfile local (build: .)
    # Esto reconstruye la imagen y reinicia el servicio.
    log_message "Reconstruyendo y reiniciando el servicio $APP_SERVICE_NAME..."
    # Necesitas que este script pueda ejecutar docker-compose en el HOST.
    # Esto se logra montando el socket de Docker y el docker-compose.yml.
    docker-compose -f /docker-compose/docker-compose.yml build $APP_SERVICE_NAME && \
    docker-compose -f /docker-compose/docker-compose.yml up -d --no-deps $APP_SERVICE_NAME || \
    { log_message "Error al actualizar el servicio $APP_SERVICE_NAME."; exit 1; }


    # Opción 2: Si usas una imagen de Docker Hub (image: tu_usuario/tu_app:latest)
    # log_message "Pulling la última imagen y reiniciando el servicio $APP_SERVICE_NAME..."
    # docker-compose -f /docker-compose/docker-compose.yml pull $APP_SERVICE_NAME && \
    # docker-compose -f /docker-compose/docker-compose.yml up -d --no-deps $APP_SERVICE_NAME || \
    # { log_message "Error al actualizar el servicio $APP_SERVICE_NAME."; exit 1; }

    # Guardar el nuevo SHA desplegado
    echo "$LATEST_REMOTE_SHA" > "$DEPLOYED_SHA_FILE"
    log_message "Actualización completada. Nuevo SHA registrado: $LATEST_REMOTE_SHA"
else
    log_message "No hay nuevas versiones. El SHA del remoto ($LATEST_REMOTE_SHA) es el mismo que el desplegado ($CURRENT_DEPLOYED_SHA)."
fi

log_message "Chequeo de versión finalizado."
```

**Comment by yellowmachine** [comment]
```yaml
# --- Nuevo Servicio para el Cron Job ---
  version_checker:
    image: alpine/git:latest # Una imagen ligera con git y bash
    volumes:
      - ./check_version.sh:/usr/local/bin/check_version.sh # Monta el script
      - /var/run/docker.sock:/var/run/docker.sock # Necesario para que el script ejecute docker commands en el host
      - ./docker-compose.yml:/docker-compose/docker-compose.yml # Para que el script encuentre tu compose file
      - ./data_for_cron:/data # Volumen para el current_deployed_sha.txt y logs (haz que sea persistente)
    environment:
      # Si tu repo es privado, necesitarás un token de GitHub
      # - GITHUB_TOKEN=ghp_YOUR_TOKEN_HERE
    command: sh -c "chmod +x /usr/local/bin/check_version.sh && while true; do /usr/local/bin/check_version.sh; sleep 300; done" # Ejecuta cada 5 minutos (300 segundos)
    # Si prefieres usar un cron real dentro del contenedor:
    # command: sh -c "chmod +x /usr/local/bin/check_version.sh && echo '*/5 * * * * /usr/local/bin/check_version.sh >> /var/log/cron.log 2>&1' | crontab - && crond -f -d 8"
    restart: always
```
